import { type NextPage } from "next";
import Head from "next/head";
import HeroContent from "~/components/HeroContent";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Quizzify</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroContent />
    </>
  );
};

export default Home;
