import { ReactNode } from "react";
import Navbar from "./Navbar";
import Head from "next/head";

function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>Quizzify</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
    </>
  );
}

export default Layout;
